# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_modular_headers!

target 'ATMVVMDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ATMVVMDemo
#  pod 'ATMVVM', :path => '../../ATMVVM'
  pod 'ATMVVM', :git => 'git@github.com:yebiaoli/ATMVVM.git', :tag => '0.1'
  pod 'SnapKit'
  pod 'LookinServer', :configurations => ['Debug']
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      
    end
  end
end


